name: Deploy to WP Engine via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SFTP (skip chmod)
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          user: ${{ secrets.SFTP_USER }}
          pass: ${{ secrets.SFTP_PASSWORD }}
          localDir: ./                       # Your mp-academy theme folder
          remoteDir: /wp-content/themes/mp-academy
          options: --reverse --verbose --no-perms
