name: Deploy Theme to WP Engine Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy theme to WP Engine staging
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: mpacademystg
          SRC_PATH: ./
          REMOTE_PATH: wp-content/themes/mp-academy/
          PHP_LINT: TRUE
          FLAGS: -azvr --inplace --delete --exclude=.* --exclude-from=.deployignore
          CACHE_CLEAR: TRUE
